### Teste do Novo Login com Validação em Cadeia
# @insecure
POST https://localhost:8443/api/contas/login
Content-Type: application/json

{
    "login": "bruno",
    "senha": "123",
    "data": "07/07/2025",
    "hora": "00:00",
    "codigo": "ABCDE"
}